// Conductor lookup, derived from ConductorListCurrent.xlsx (bare conductors).
// est:true => diameter ESTIMATED from CSA; replace with datasheet/measured values.
export const TABLE = [
  {name:"\u2014", cons:"7/.016", type:"Cu HD", mat:"Copper", csa:1, dia:1.22, est:false},
  {name:"\u2014", cons:"7/.044", type:"Cu HD", mat:"Copper", csa:6, dia:3.35, est:false},
  {name:"\u2014", cons:"7/.052", type:"Cu HD", mat:"Copper", csa:9, dia:3.96, est:false},
  {name:"\u2014", cons:"7/.064", type:"Cu HD", mat:"Copper", csa:15, dia:4.88, est:false},
  {name:"\u2014", cons:"7/.080", type:"Cu HD", mat:"Copper", csa:23, dia:6.1, est:false},
  {name:"\u2014", cons:"7/.083", type:"Cu HD", mat:"Copper", csa:24, dia:6.32, est:false},
  {name:"\u2014", cons:"7/.092", type:"Cu HD", mat:"Copper", csa:30, dia:7.01, est:false},
  {name:"\u2014", cons:"7/.096", type:"Cu HD", mat:"Copper", csa:33, dia:7.32, est:false},
  {name:"\u2014", cons:"7/.104", type:"Cu HD", mat:"Copper", csa:38, dia:7.92, est:false},
  {name:"\u2014", cons:"7/.116", type:"Cu HD", mat:"Copper", csa:48, dia:8.84, est:false},
  {name:"\u2014", cons:"7/.136", type:"Cu HD", mat:"Copper", csa:66, dia:10.36, est:false},
  {name:"\u2014", cons:"19/.064", type:"Cu HD", mat:"Copper", csa:40, dia:8.13, est:false},
  {name:"\u2014", cons:"19/.072", type:"Cu HD", mat:"Copper", csa:50, dia:9.14, est:false},
  {name:"\u2014", cons:"19/.080", type:"Cu HD", mat:"Copper", csa:61, dia:10.16, est:false},
  {name:"\u2014", cons:"7/3.05", type:"SCAC", mat:"Aluminium", csa:50, dia:9.15, est:false},
  {name:"Namu", cons:"Namu", type:"AAC", mat:"Aluminium", csa:25, dia:6.4, est:true},
  {name:"Kutu", cons:"Kutu", type:"AAC", mat:"Aluminium", csa:50, dia:9.15, est:true},
  {name:"Rango", cons:"Rango", type:"AAC", mat:"Aluminium", csa:73, dia:11.06, est:true},
  {name:"Weke", cons:"Weke", type:"AAC", mat:"Aluminium", csa:122, dia:14.3, est:true},
  {name:"Chlorine", cons:"Chlorine", type:"AAAC", mat:"Aluminium", csa:34, dia:7.46, est:true},
  {name:"Fluorine", cons:"Fluorine", type:"AAAC", mat:"Aluminium", csa:50, dia:9.15, est:true},
  {name:"Helium", cons:"Helium", type:"AAAC", mat:"Aluminium", csa:77, dia:11.36, est:true},
  {name:"Iodine", cons:"Iodine", type:"AAAC", mat:"Aluminium", csa:124, dia:14.41, est:true},
  {name:"Neon", cons:"Neon", type:"AAAC", mat:"Aluminium", csa:210, dia:18.82, est:true},
  {name:"Oxygen", cons:"Oxygen", type:"AAAC", mat:"Aluminium", csa:320, dia:23.23, est:true},
  {name:"Mullet", cons:"Mullet", type:"ACSR", mat:"Aluminium", csa:10, dia:4.37, est:true},
  {name:"Thrush", cons:"Thrush", type:"ACSR", mat:"Aluminium", csa:18, dia:5.86, est:true},
  {name:"Flounder", cons:"Flounder", type:"ACSR", mat:"Aluminium", csa:20, dia:6.18, est:true},
  {name:"Squirrel", cons:"Squirrel", type:"ACSR", mat:"Aluminium", csa:21, dia:6.33, est:false},
  {name:"Snipe", cons:"Snipe", type:"ACSR", mat:"Aluminium", csa:25, dia:6.91, est:true},
  {name:"Ferret", cons:"Ferret", type:"ACSR", mat:"Aluminium", csa:42, dia:9.00, est:false},
  {name:"Mink", cons:"Mink", type:"ACSR", mat:"Aluminium", csa:63, dia:10.98, est:false},
  {name:"Waxwing", cons:"Waxwing", type:"ACSR", mat:"Aluminium", csa:135, dia:16.57, est:true},
  {name:"Dog", cons:"Dog", type:"ACSR", mat:"Aluminium", csa:103, dia:14.15, est:false},
  {name:"Jaguar", cons:"Jaguar", type:"ACSR", mat:"Aluminium", csa:200, dia:20.17, est:true}
];
